theme: jekyll-theme-cayman
title: Welcome to FACTum Studio! 
description: FACTum Studio is a tool support for Architectural Design Patterns spesfication and verification with the support of
interactive verification in Isabelle/HOL.
